
# Default build: psp2d, pspnet, pspsnd
# If using OSLIB disable PSP2D and PSPSND

WITH_PSP2D = 1
WITH_PSPSND = 1
WITH_PSPNET = 1
WITH_OSLIB = 0
WITH_SQLITE = 1
WITH_PSPOGG = 1
WITH_PSPMP3 = 1
WITH_SSL = 0     # SSL not working yet

include Makefile.base
