// Generated by generr.py. Do not edit.


char* formatPSPError(int code)
{
    switch (code)
    {
        case 2147614721U:
            return "ERROR";

        case 2147614722U:
            return "NOTIMP";

        case 2147614770U:
            return "ILLEGAL_EXPCODE";

        case 2147614771U:
            return "EXPHANDLER_NOUSE";

        case 2147614772U:
            return "EXPHANDLER_USED";

        case 2147614773U:
            return "SYCALLTABLE_NOUSED";

        case 2147614774U:
            return "SYCALLTABLE_USED";

        case 2147614775U:
            return "ILLEGAL_SYSCALLTABLE";

        case 2147614776U:
            return "ILLEGAL_PRIMARY_SYSCALL_NUMBER";

        case 2147614777U:
            return "PRIMARY_SYSCALL_NUMBER_INUSE";

        case 2147614820U:
            return "ILLEGAL_CONTEXT";

        case 2147614821U:
            return "ILLEGAL_INTRCODE";

        case 2147614822U:
            return "CPUDI";

        case 2147614823U:
            return "FOUND_HANDLER";

        case 2147614824U:
            return "NOTFOUND_HANDLER";

        case 2147614825U:
            return "ILLEGAL_INTRLEVEL";

        case 2147614826U:
            return "ILLEGAL_ADDRESS";

        case 2147614827U:
            return "ILLEGAL_INTRPARAM";

        case 2147614828U:
            return "ILLEGAL_STACK_ADDRESS";

        case 2147614829U:
            return "ALREADY_STACK_SET";

        case 2147614870U:
            return "NO_TIMER";

        case 2147614871U:
            return "ILLEGAL_TIMERID";

        case 2147614872U:
            return "ILLEGAL_SOURCE";

        case 2147614873U:
            return "ILLEGAL_PRESCALE";

        case 2147614874U:
            return "TIMER_BUSY";

        case 2147614875U:
            return "TIMER_NOT_SETUP";

        case 2147614876U:
            return "TIMER_NOT_INUSE";

        case 2147614880U:
            return "UNIT_USED";

        case 2147614881U:
            return "UNIT_NOUSE";

        case 2147614882U:
            return "NO_ROMDIR";

        case 2147614920U:
            return "IDTYPE_EXIST";

        case 2147614921U:
            return "IDTYPE_NOT_EXIST";

        case 2147614922U:
            return "IDTYPE_NOT_EMPTY";

        case 2147614923U:
            return "UNKNOWN_UID";

        case 2147614924U:
            return "UNMATCH_UID_TYPE";

        case 2147614925U:
            return "ID_NOT_EXIST";

        case 2147614926U:
            return "NOT_FOUND_UIDFUNC";

        case 2147614927U:
            return "UID_ALREADY_HOLDER";

        case 2147614928U:
            return "UID_NOT_HOLDER";

        case 2147614929U:
            return "ILLEGAL_PERM";

        case 2147614930U:
            return "ILLEGAL_ARGUMENT";

        case 2147614931U:
            return "ILLEGAL_ADDR";

        case 2147614932U:
            return "OUT_OF_RANGE";

        case 2147614933U:
            return "MEM_RANGE_OVERLAP";

        case 2147614934U:
            return "ILLEGAL_PARTITION";

        case 2147614935U:
            return "PARTITION_INUSE";

        case 2147614936U:
            return "ILLEGAL_MEMBLOCKTYPE";

        case 2147614937U:
            return "MEMBLOCK_ALLOC_FAILED";

        case 2147614938U:
            return "MEMBLOCK_RESIZE_LOCKED";

        case 2147614939U:
            return "MEMBLOCK_RESIZE_FAILED";

        case 2147614940U:
            return "HEAPBLOCK_ALLOC_FAILED";

        case 2147614941U:
            return "HEAP_ALLOC_FAILED";

        case 2147614942U:
            return "ILLEGAL_CHUNK_ID";

        case 2147614943U:
            return "NOCHUNK";

        case 2147614944U:
            return "NO_FREECHUNK";

        case 2147615020U:
            return "LINKERR";

        case 2147615021U:
            return "ILLEGAL_OBJECT";

        case 2147615022U:
            return "UNKNOWN_MODULE";

        case 2147615023U:
            return "NOFILE";

        case 2147615024U:
            return "FILEERR";

        case 2147615025U:
            return "MEMINUSE";

        case 2147615026U:
            return "PARTITION_MISMATCH";

        case 2147615027U:
            return "ALREADY_STARTED";

        case 2147615028U:
            return "NOT_STARTED";

        case 2147615029U:
            return "ALREADY_STOPPED";

        case 2147615030U:
            return "CAN_NOT_STOP";

        case 2147615031U:
            return "NOT_STOPPED";

        case 2147615032U:
            return "NOT_REMOVABLE";

        case 2147615033U:
            return "EXCLUSIVE_LOAD";

        case 2147615034U:
            return "LIBRARY_NOT_YET_LINKED";

        case 2147615035U:
            return "LIBRARY_FOUND";

        case 2147615036U:
            return "LIBRARY_NOTFOUND";

        case 2147615037U:
            return "ILLEGAL_LIBRARY";

        case 2147615038U:
            return "LIBRARY_INUSE";

        case 2147615039U:
            return "ALREADY_STOPPING";

        case 2147615040U:
            return "ILLEGAL_OFFSET";

        case 2147615041U:
            return "ILLEGAL_POSITION";

        case 2147615042U:
            return "ILLEGAL_ACCESS";

        case 2147615043U:
            return "MODULE_MGR_BUSY";

        case 2147615044U:
            return "ILLEGAL_FLAG";

        case 2147615045U:
            return "CANNOT_GET_MODULELIST";

        case 2147615046U:
            return "PROHIBIT_LOADMODULE_DEVICE";

        case 2147615047U:
            return "PROHIBIT_LOADEXEC_DEVICE";

        case 2147615048U:
            return "UNSUPPORTED_PRX_TYPE";

        case 2147615049U:
            return "ILLEGAL_PERM_CALL";

        case 2147615050U:
            return "CANNOT_GET_MODULE_INFORMATION";

        case 2147615051U:
            return "ILLEGAL_LOADEXEC_BUFFER";

        case 2147615052U:
            return "ILLEGAL_LOADEXEC_FILENAME";

        case 2147615053U:
            return "NO_EXIT_CALLBACK";

        case 2147615120U:
            return "NO_MEMORY";

        case 2147615121U:
            return "ILLEGAL_ATTR";

        case 2147615122U:
            return "ILLEGAL_ENTRY";

        case 2147615123U:
            return "ILLEGAL_PRIORITY";

        case 2147615124U:
            return "ILLEGAL_STACK_SIZE";

        case 2147615125U:
            return "ILLEGAL_MODE";

        case 2147615126U:
            return "ILLEGAL_MASK";

        case 2147615127U:
            return "ILLEGAL_THID";

        case 2147615128U:
            return "UNKNOWN_THID";

        case 2147615129U:
            return "UNKNOWN_SEMID";

        case 2147615130U:
            return "UNKNOWN_EVFID";

        case 2147615131U:
            return "UNKNOWN_MBXID";

        case 2147615132U:
            return "UNKNOWN_VPLID";

        case 2147615133U:
            return "UNKNOWN_FPLID";

        case 2147615134U:
            return "UNKNOWN_MPPID";

        case 2147615135U:
            return "UNKNOWN_ALMID";

        case 2147615136U:
            return "UNKNOWN_TEID";

        case 2147615137U:
            return "UNKNOWN_CBID";

        case 2147615138U:
            return "DORMANT";

        case 2147615139U:
            return "SUSPEND";

        case 2147615140U:
            return "NOT_DORMANT";

        case 2147615141U:
            return "NOT_SUSPEND";

        case 2147615142U:
            return "NOT_WAIT";

        case 2147615143U:
            return "CAN_NOT_WAIT";

        case 2147615144U:
            return "WAIT_TIMEOUT";

        case 2147615145U:
            return "WAIT_CANCEL";

        case 2147615146U:
            return "RELEASE_WAIT";

        case 2147615147U:
            return "NOTIFY_CALLBACK";

        case 2147615148U:
            return "THREAD_TERMINATED";

        case 2147615149U:
            return "SEMA_ZERO";

        case 2147615150U:
            return "SEMA_OVF";

        case 2147615151U:
            return "EVF_COND";

        case 2147615152U:
            return "EVF_MULTI";

        case 2147615153U:
            return "EVF_ILPAT";

        case 2147615154U:
            return "MBOX_NOMSG";

        case 2147615155U:
            return "MPP_FULL";

        case 2147615156U:
            return "MPP_EMPTY";

        case 2147615157U:
            return "WAIT_DELETE";

        case 2147615158U:
            return "ILLEGAL_MEMBLOCK";

        case 2147615159U:
            return "ILLEGAL_MEMSIZE";

        case 2147615160U:
            return "ILLEGAL_SPADADDR";

        case 2147615161U:
            return "SPAD_INUSE";

        case 2147615162U:
            return "SPAD_NOT_INUSE";

        case 2147615163U:
            return "ILLEGAL_TYPE";

        case 2147615164U:
            return "ILLEGAL_SIZE";

        case 2147615165U:
            return "ILLEGAL_COUNT";

        case 2147615166U:
            return "UNKNOWN_VTID";

        case 2147615167U:
            return "ILLEGAL_VTID";

        case 2147615168U:
            return "ILLEGAL_KTLSID";

        case 2147615169U:
            return "KTLS_FULL";

        case 2147615170U:
            return "KTLS_BUSY";

        case 2147615320U:
            return "PM_INVALID_PRIORITY";

        case 2147615321U:
            return "PM_INVALID_DEVNAME";

        case 2147615322U:
            return "PM_UNKNOWN_DEVNAME";

        case 2147615323U:
            return "PM_PMINFO_REGISTERED";

        case 2147615324U:
            return "PM_PMINFO_UNREGISTERED";

        case 2147615325U:
            return "PM_INVALID_MAJOR_STATE";

        case 2147615326U:
            return "PM_INVALID_REQUEST";

        case 2147615327U:
            return "PM_UNKNOWN_REQUEST";

        case 2147615328U:
            return "PM_INVALID_UNIT";

        case 2147615329U:
            return "PM_CANNOT_CANCEL";

        case 2147615330U:
            return "PM_INVALID_PMINFO";

        case 2147615331U:
            return "PM_INVALID_ARGUMENT";

        case 2147615332U:
            return "PM_ALREADY_TARGET_PWRSTATE";

        case 2147615333U:
            return "PM_CHANGE_PWRSTATE_FAILED";

        case 2147615334U:
            return "PM_CANNOT_CHANGE_DEVPWR_STATE";

        case 2147615335U:
            return "PM_NO_SUPPORT_DEVPWR_STATE";

        case 2147615420U:
            return "DMAC_REQUEST_FAILED";

        case 2147615421U:
            return "DMAC_REQUEST_DENIED";

        case 2147615422U:
            return "DMAC_OP_QUEUED";

        case 2147615423U:
            return "DMAC_OP_NOT_QUEUED";

        case 2147615424U:
            return "DMAC_OP_RUNNING";

        case 2147615425U:
            return "DMAC_OP_NOT_ASSIGNED";

        case 2147615426U:
            return "DMAC_OP_TIMEOUT";

        case 2147615427U:
            return "DMAC_OP_FREED";

        case 2147615428U:
            return "DMAC_OP_USED";

        case 2147615429U:
            return "DMAC_OP_EMPTY";

        case 2147615430U:
            return "DMAC_OP_ABORTED";

        case 2147615431U:
            return "DMAC_OP_ERROR";

        case 2147615432U:
            return "DMAC_CHANNEL_RESERVED";

        case 2147615433U:
            return "DMAC_CHANNEL_EXCLUDED";

        case 2147615434U:
            return "DMAC_PRIVILEGE_ADDRESS";

        case 2147615435U:
            return "DMAC_NO_ENOUGHSPACE";

        case 2147615436U:
            return "DMAC_CHANNEL_NOT_ASSIGNED";

        case 2147615437U:
            return "DMAC_CHILD_OPERATION";

        case 2147615438U:
            return "DMAC_TOO_MUCH_SIZE";

        case 2147615439U:
            return "DMAC_INVALID_ARGUMENT";

        case 2147615520U:
            return "MFILE";

        case 2147615521U:
            return "NODEV";

        case 2147615522U:
            return "XDEV";

        case 2147615523U:
            return "BADF";

        case 2147615524U:
            return "INVAL";

        case 2147615525U:
            return "UNSUP";

        case 2147615526U:
            return "ALIAS_USED";

        case 2147615527U:
            return "CANNOT_MOUNT";

        case 2147615528U:
            return "DRIVER_DELETED";

        case 2147615529U:
            return "ASYNC_BUSY";

        case 2147615530U:
            return "NOASYNC";

        case 2147615531U:
            return "REGDEV";

        case 2147615532U:
            return "NOCWD";

        case 2147615533U:
            return "NAMETOOLONG";

        case 2147615720U:
            return "NXIO";

        case 2147615721U:
            return "IO";

        case 2147615722U:
            return "NOMEM";

        case 2147615723U:
            return "STDIO_NOT_OPENED";

        case 2147615820U:
            return "CACHE_ALIGNMENT";

        case 2147615821U:
            return "ERRORMAX";

        default:
            return "UNKNOWN_ERROR";
    }
}
